### PR TITLE
Nns v21 spoofing patches

### LINKED ISSUE #607: Android 14 signature spoofing patch fails due to API changes
Hello!

* Device: lemonadep
* Branch: lineage-21

The Android 14 signature spoofing patches fail to compile. The error seems to be:

```
FAILED: out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api-stubs-docs-non-updatable-stubs.srcjar out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api-stubs-docs-non-updatable_annotations.zip out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api-stubs-docs-non-updatable_api.txt out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api-stubs-docs-non-updatable_removed.txt out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api_lint.timestamp out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api_lint_baseline.txt out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api_lint_report.txt out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/check_last_released_api.timestamp out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/last_released_baseline.txt
out/host/linux-x86/bin/sbox --sandbox-path out/soong/.temp --output-dir out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava --manifest out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava.sbox.textproto --write-if-changed
The failing command was run inside an sbox sandbox in temporary directory
out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95
The failing command line can be found in
out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95/sbox_command.0.bash
out/srcjars/android/Manifest.java:2770: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission.FAKE_PACKAGE_SIGNATURE [UnflaggedApi]
out/srcjars/android/Manifest.java:6391: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission_group.FAKE_PACKAGE [UnflaggedApi]
Error: metalava detected the following problems:
out/srcjars/android/Manifest.java:2770: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission.FAKE_PACKAGE_SIGNATURE [UnflaggedApi]
out/srcjars/android/Manifest.java:6391: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission_group.FAKE_PACKAGE [UnflaggedApi]
metalava wrote updated baseline to /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95/./out/api_lint_baseline.txt
metalava wrote updated baseline to /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95/./out/last_released_baseline.txt
************************************************************
Your API changes are triggering API Lint warnings or errors.
To make these errors go away, fix the code according to the
error and/or warning messages above.

If it is not possible to do so, there are workarounds:

1. You can suppress the errors with @SuppressLint("<id>")
   where the <id> is given in brackets in the error message above.
2. You can update the baseline by executing the following
   command:
       (cd $ANDROID_BUILD_TOP && cp \
       "out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api_lint_baseline.txt" \
       "frameworks/base/core/api/lint-baseline.txt")
   To submit the revised baseline.txt to the main Android
   repository, you will need approval.
************************************************************
exit status 255
```

Full log can be found here: [lineage-21.0-20240408-nns-lemonadep.log.gz](https://github.com/lineageos4microg/docker-lineage-cicd/files/14915112/lineage-21.0-20240408-nns-lemonadep.log.gz)

I'm aware that LineageOS now ships with a signature spoofing feature built-in, however, this only applies to _debuggable_ builds (such as userdebug) and not regular _user_ builds. I have to use _user_ builds for technical reasons, so I would appreciate if it were still possible to apply the signature spoofing patch.

I can alternatively write another patch which enables the built-in signature spoofing even in _user_ builds. However, I'm unsure how I would do this - where are patches supposed to go and what are they supposed to look like so that they would be picked up by the build system, is there any documentation for this? Thanks.

### LINKED ISSUE #614: LOS Signature spoofing changes don't work for `user` builds
The original description of #607 conflates two issues
1. ***Our*** signature spoofing patches fail to build because of the missing `@FlaggedAPI` annotation for the new APIs
2. The upstream changes which allow signature spoofing only work for 'debuggable` builds (e.g. `userdebug`) and not for `user` builds.

IMO the two issue are separate, and should be fixed separately. 
1: is addressed in #607 

This issue is to track 2.

The changes in the `nns-v21-spoofing-patches` branch and PR #612 fixes this issue but doesn't fix 1; it removes the patches rather than fixing them. 

_Originally posted by @petefoth in https://github.com/lineageos4microg/docker-lineage-cicd/issues/607#issuecomment-2070874499_

### PR DESCRIPTION
**Pull request by petefoth**
These changes are intended to fix #614 , but thy need to be tested further before they can be merged to `master` branch.

The changes have apparently been used to make a `user` build. They need to be tested to ensure that they do not affect other build types, in particular the `userdebug` builds that are the default

Please add details of what testing has been done in comments

### CODE REVIEW

**Comment by gwstorm** [comment]
I'm giving this a go now, however, this is the only thing I use docker for, so I'm not well versed in it at all. Is it just a simple as changing the image to `image: lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches`?

**Comment by petefoth** [comment]
> Is it just a simple as changing the image to `image: lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches`?

Yes. Just change the last statement in the `docker run` command to `lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches' instead of ``lineageos4microg/docker-lineage-cicd`

**Comment by gwstorm** [comment]
Okay, I did that yesterday when I posted my first response and this is what I got - 

<details>
<summary>API Error</summary>

> The failing command was run inside an sbox sandbox in temporary directory
> out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95
> The failing command line can be found in
> out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95/sbox_command.0.bash
> out/srcjars/android/Manifest.java:2770: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission.FAKE_PACKAGE_SIGNATURE [UnflaggedApi]
> out/srcjars/android/Manifest.java:6391: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission_group.FAKE_PACKAGE [UnflaggedApi]
> Error: metalava detected the following problems:
> out/srcjars/android/Manifest.java:2770: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission.FAKE_PACKAGE_SIGNATURE [UnflaggedApi]
> out/srcjars/android/Manifest.java:6391: error: New API must be flagged with @FlaggedApi: field android.Manifest.permission_group.FAKE_PACKAGE [UnflaggedApi]
> metalava wrote updated baseline to /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95/./out/api_lint_baseline.txt
> metalava wrote updated baseline to /srv/src/LINEAGE_21_0/out/soong/.temp/sbox/dcabbf69fbe8e32ae16e786d21b129ef1759ab95/./out/last_released_baseline.txt
> ************************************************************
> Your API changes are triggering API Lint warnings or errors.
> To make these errors go away, fix the code according to the
> error and/or warning messages above.
> 
> If it is not possible to do so, there are workarounds:
> 
> 1. You can suppress the errors with @SuppressLint("<id>")
>    where the <id> is given in brackets in the error message above.
> 2. You can update the baseline by executing the following
>    command:
>        (cd $ANDROID_BUILD_TOP && cp \
>        "out/soong/.intermediates/frameworks/base/api/api-stubs-docs-non-updatable/android_common/metalava/api_lint_baseline.txt" \
>        "frameworks/base/core/api/lint-baseline.txt")
>    To submit the revised baseline.txt to the main Android
>    repository, you will need approval.
> ************************************************************
> exit status 255

</details>

Here's my compose configuration just to make sure I'm doing what you want -

```
version: '3.9'
services:
    docker-lineage-cicd:
        environment:
            - BRANCH_NAME=lineage-21.0
            - DEVICE_LIST=lemonadep
            - SIGN_BUILDS=true
            - SIGNATURE_SPOOFING=restricted
            - WITH_GMS=true
            - INCLUDE_PROPRIETARY=true
            - OTA_URL=[redacted]
            - DELETE_OLD_ZIPS=2
        volumes:
            - '/mnt/cache/lineage/src:/srv/src'
            - '/mnt/cache/lineage/zips:/srv/zips'
            - '/mnt/cache/lineage/logs:/srv/logs'
            - '/mnt/cache/lineage/ccache:/srv/ccache'
            - '/mnt/cache/lineage/keys:/srv/keys'
            - '/mnt/cache/lineage/local_manifests:/srv/local_manifests'
        image: lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches
```

**Comment by FintasticMan** [comment]
Not sure how that happened, that error shouldn't be possible on this branch. You should get the warning `WARNING: Signature spoofing patches requested, but branch (lineage-21.0) does not support microG patches`, but no errors. All I can imagine is that somehow it's still using the master docker image. Can you run `docker images` and see what images you have pulled? If you don't have the nns-v21-spoofing-patches one, run `docker pull lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches`, and if you do see the latest one, maybe try `docker rmi lineageos4microg/docker-lineage-cicd:latest`.

**Comment by gwstorm** [comment]
Got it, I _did_ have a lingering image that I've now removed. After removing that, I was getting this response from docker - 

```
docker-lineage-cicd-1  | Set cache size limit to 50.0 GB
docker-lineage-cicd-1  | >> [Mon Apr 22 17:24:55 UTC 2024] Branch:  lineage-21.0
docker-lineage-cicd-1  | >> [Mon Apr 22 17:24:55 UTC 2024] Devices: lemonadep,
docker-lineage-cicd-1  | >> [Mon Apr 22 17:24:56 UTC 2024] (Re)initializing branch repository
docker-lineage-cicd-1  | >> [Mon Apr 22 17:24:57 UTC 2024] Copying '/srv/local_manifests/*.xml' to '.repo/local_manifests/'
docker-lineage-cicd-1  | >> [Mon Apr 22 17:24:57 UTC 2024] Syncing branch repository
docker-lineage-cicd-1  | >> [Mon Apr 22 17:26:27 UTC 2024] Calling git lfs pull disabled
docker-lineage-cicd-1  | /root/build.sh: line 299: frameworks_base_patch: unbound variable
docker-lineage-cicd-1 exited with code 1
```

[Which does seem to reference signature spoofing ](https://github.com/lineageos4microg/docker-lineage-cicd/blob/master/src/build.sh#L297C1-L303C11)

I doubt it will do anything, but in the mean time, I've just removed the `src` folder so I can make sure everything is fresh on my current attempt.

**Comment by FintasticMan** [comment]
ah ok, then we'll need to explicitly set the variable

File: src/build.sh [hunk 1]
```diff
@@ -175,24 +175,26 @@ for branch in ${BRANCH_NAME//,/ }; do
...
         frameworks_base_patch="android_frameworks_base-Android13.patch"
         modules_permission_patch="packages_modules_Permission-Android13.patch"
+        user_build_spoofing_patch="android_frameworks_base-user_build.patch"
         ;;
       lineage-21.0*)
         themuppets_branch="lineage-21.0"
         android_version="14"
-        frameworks_base_patch="android_frameworks_base-Android14.patch"
-        modules_permission_patch="packages_modules_Permission-Android14.patch"
+        user_build_spoofing_patch="android_frameworks_base-user_build.patch"
```
Comment (FintasticMan) [inline src/build.sh:197]:
```suggestion
        frameworks_base_patch=""
        user_build_spoofing_patch="android_frameworks_base-user_build.patch"
```

**Review by FintasticMan — CHANGES_REQUESTED** [review]

File: src/signature_spoofing_patches/packages_modules_Permission-Android14.patch
Comment (petefoth) [inline src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: Is this change no longer needed in Android 14 / lineage-21 for our userdebug builds?

Comment (FintasticMan) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: no, not needed. it's only needed for our patches, not for the los's builtin sigspoofing.

Comment (petefoth) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: > it's only needed for our patches, not for los's builtin sigspoofing.

That was not my question. The original issue #607 concerns `user` builds, not the `userdebug` builds that are the default, and that the project builds and publishes. I have asked a question there about whether the problem - the patch not compiling - occurred only in `user` builds, or whether it occurs also in `userdebug` builds.

One effect of this change is to remove the possibility of 'unrestricted` spoofing in 21.0 and later builds. I'm not completely happy about that, unless we really have no choice. At the moment, my inclination is ***not*** to merge this change to `master`, and to say that users who wish to make `user` builds should use the `nns-v21-spoofing-patches` branch.

I'm open to persuasion, but I would need convincing 😄 




So this change would mean that our patches cannot be used, and that 'unrestricted` signature spoofing will not be possible for 21.0 and later builds. I'm not totally happy with that change.

Comment (FintasticMan) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: The patches also don't compile in userdebug builds. I understand that no unrestricted patches is annoying, but I'm not aware of any ports of them to LOS 21, so it doesn't make sense to publish broken ones IMO.

Comment (petefoth) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: > The patches also don't compile in userdebug builds

In which case my first response would be to fix that :) I'm looking into the use of `@FlaggedAPI`, and whether it would be enough to add it in our patches.

If that ***is*** all that is needed, then it's a much simpler fix that the changes in this PR

> it doesn't make sense to publish broken ones IMO.

Agreed. Until we agree on a fix, and get it implemented, tested and pushed to `master`, then we should suggest that users who want / need signature spoofing in `user` builds should use the `nns-v21-spoofing-patches` branch

I'll continue discussing this in #607

Comment (FintasticMan) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: I would suggest that merging this (after testing it definitely works) and then potentially re-adding working patches would be the best course of action. All this does is improve compatibility on the whole, which I think is definitely a good thing.

Comment (petefoth) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: Sorry but I disagree. The fix for #607 looks to be straightforward: just add the `@FlaggedAPI` annotation to the 'new' APIs in the patch. I will try and get that implemented today. 

I am happy for the other changes in this PR to be used to fix 'LOS Signature spoofing changes don't work for user builds' #614. That can either be done and tested in a new branch, or by modifying this PR so that it only deals with the `user` builds issue

File: src/build.sh (hunk 1 above)
Comment (FintasticMan) [reply src/build.sh:199]: Resolved by #615.

File: src/signature_spoofing_patches/packages_modules_Permission-Android14.patch
Comment (FintasticMan) [reply src/signature_spoofing_patches/packages_modules_Permission-Android14.patch:1]: Resolved by #615. This branch now only deals with the `user` builds issue.

**Comment by petefoth** [comment]
> They need to be tested to ensure that they do not affect other build types, in particular the `userdebug` builds that are the default
> 
> Please add details of what testing has been done in comments

Has anyone done any testing with this change (i.e. using the `lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches` to make `userdebug` builds? I don't want to merge to master until that is done

**Comment by gwstorm** [comment]
> Has anyone done any testing with this change (i.e. using the `lineageos4microg/docker-lineage-cicd:nns-v21-spoofing-patches` to make `userdebug` builds? I don't want to merge to master until that is done

I just finished a successful build and install. Everything is working here!

**Comment by petefoth** [comment]
> I just finished a successful build and install. Everything is working here!

Thanks @gwstorm @FintasticMan @nnsee for your efforts in getting this one sorted.

Merged
